services:
  sunday:
    image: ghcr.io/rezi-labs/sunday:latest
    container_name: sunday
    environment:
      LOCAL: "true"
      FAKE_AI: "true"
      API_KEY_ONE: "very-secure-one"
      API_KEY_TWO: "very-secure-two"
      RUST_LOG: "debug"
    ports:
      - "3000:3000"
    restart: unless-stopped
